# tests/unit/services/policies/test_symlink_policy.py
"""Unit tests for SymlinkPolicy."""

from pathlib import Path

import pytest

from repo2xml.config import SymlinkFilesMode
from repo2xml.domain.model import ClassificationResult, FileEntry, LinkPayload, SkipCode, SkippedPayload
from repo2xml.services.policies import SymlinkPolicy


class TestSymlinkPolicy:
    @pytest.fixture
    def entry(self) -> FileEntry:
        return FileEntry(
            abs_path=Path("/repo/link"),
            rel_path="link",
            name="link",
            size=0,
            mtime_ns=0,
            is_symlink=True,
            symlink_target="/target",
        )

    @pytest.fixture
    def classification(self) -> ClassificationResult:
        return ClassificationResult(kind="text")

    def test_as_link_returns_link_payload(self, entry: FileEntry, classification: ClassificationResult) -> None:
        policy = SymlinkPolicy(SymlinkFilesMode.as_link)
        result = policy.apply(entry, classification)
        assert isinstance(result, LinkPayload)
        assert result.link_target == "/target"

    def test_skip_returns_skipped_payload(self, entry: FileEntry, classification: ClassificationResult) -> None:
        policy = SymlinkPolicy(SymlinkFilesMode.skip)
        result = policy.apply(entry, classification)
        assert isinstance(result, SkippedPayload)
        assert result.code == SkipCode.unknown
        # The message is generated by ReasonFormatter and is "Skipped" for unknown codes.
        # We don't assert on the message content to avoid coupling.

    def test_follow_returns_none(self, entry: FileEntry, classification: ClassificationResult) -> None:
        policy = SymlinkPolicy(SymlinkFilesMode.follow)
        result = policy.apply(entry, classification)
        assert result is None

    def test_regular_file_ignored(self, classification: ClassificationResult) -> None:
        entry = FileEntry(
            abs_path=Path("/repo/file.txt"),
            rel_path="file.txt",
            name="file.txt",
            size=100,
            mtime_ns=0,
            is_symlink=False,
        )
        policy = SymlinkPolicy(SymlinkFilesMode.as_link)
        result = policy.apply(entry, classification)
        assert result is None